# Even Fibonacci numbers
# Problem 2
# Each new term in the Fibonacci sequence
# is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence
# whose values do not exceed four million, find the sum of the even-valued terms.

class Fibonacci:
    def __init__(self):
        self.f2 = 1
        self.f3 = 2

    def __iter__(self):
        return self

    def __next__(self):
        self.f1 = self.f2
        self.f2 = self.f3
        self.f3 = self.f1+self.f2
        return self.f1

sum = 0 #  sum of even-valued terms

F = Fibonacci()
fib = iter(F)

while True:
    fibon = next(fib)
    if fibon >= 4000000:
        break
    if fibon % 2 == 0:
        sum += fibon

print(sum)
